import streamlit as st
from PIL import Image
from transformers import pipeline
from gtts import gTTS
import tempfile
import os

st.set_page_config(
    page_title="AI Storytelling App for Kids",
    page_icon="🌈",
    layout="centered"
)


# ---------------------------------------------------------
# Custom CSS
# This section makes the interface more child-friendly.
# It uses larger fonts, colorful boxes, and bigger buttons.
# ---------------------------------------------------------
st.markdown(
    """
    <style>
    .main {
        background-color: #FFF8DC;
    }

    h1 {
        text-align: center;
        color: #FF6F61;
        font-size: 42px;
    }

    h2, h3 {
        color: #4B7BEC;
    }

    .stButton > button {
        width: 100%;
        height: 60px;
        font-size: 24px;
        font-weight: bold;
        border-radius: 20px;
        background-color: #FFCE54;
        color: #333333;
        border: 3px solid #F6B93B;
    }

    .stButton > button:hover {
        background-color: #FFD966;
        color: #000000;
        border: 3px solid #E58E26;
    }

    .story-box {
        background-color: #E8F8F5;
        padding: 20px;
        border-radius: 20px;
        border: 3px solid #55E6C1;
        font-size: 20px;
        line-height: 1.6;
        color: #2C3A47;
    }

    .caption-box {
        background-color: #FDEBD0;
        padding: 15px;
        border-radius: 15px;
        border: 2px solid #F5B041;
        font-size: 18px;
        color: #2C3A47;
    }

    .tip-box {
        background-color: #F4ECF7;
        padding: 15px;
        border-radius: 15px;
        border: 2px solid #BB8FCE;
        font-size: 17px;
        color: #2C3A47;
    }
    </style>
    """,
    unsafe_allow_html=True
)


# ---------------------------------------------------------
# Load the image captioning model
# The @st.cache_resource decorator prevents the model from
# reloading every time the user interacts with the page.
# ---------------------------------------------------------
@st.cache_resource
def load_captioning_model():
    """
    Load a pre-trained image captioning model from Hugging Face.

    Returns:
        A Hugging Face image-to-text pipeline.
    """
    captioning_model = pipeline(
        "image-to-text",
        model="Salesforce/blip-image-captioning-base"
    )
    return captioning_model


# ---------------------------------------------------------
# Load the story generation model
# This model expands the image caption into a short story.
# ---------------------------------------------------------
@st.cache_resource
def load_story_model():
    """
    Load a pre-trained text generation model from Hugging Face.

    Returns:
        A Hugging Face text-generation pipeline.
    """
    story_model = pipeline(
        "text-generation",
        model="distilgpt2"
    )
    return story_model


# ---------------------------------------------------------
# Generate an image caption
# This function takes the uploaded image and creates a short
# text description of what appears in the image.
# ---------------------------------------------------------
def generate_caption(image, captioning_model):
    """
    Generate a caption from the uploaded image.

    Args:
        image: PIL image uploaded by the user.
        captioning_model: Hugging Face image-to-text pipeline.

    Returns:
        A string caption describing the image.
    """
    result = captioning_model(image)

    if result and isinstance(result, list):
        caption = result[0].get("generated_text", "")
        return caption

    return "A beautiful picture full of imagination."


# ---------------------------------------------------------
# Generate a child-friendly story
# This function uses the image caption to create a short story.
# The story is designed for children aged 3-10.
# ---------------------------------------------------------
def generate_story(caption, story_model):
    """
    Generate a 50-100 word story based on the image caption.

    Args:
        caption: The image caption generated by the captioning model.
        story_model: Hugging Face text-generation pipeline.

    Returns:
        A child-friendly short story.
    """

    prompt = (
        "Write a cheerful, simple, and magical story for children aged 3 to 10. "
        "The story should be 50 to 100 words. "
        "Use kind and positive language. "
        f"The story is based on this picture: {caption}. "
        "Story:"
    )

    result = story_model(
        prompt,
        max_new_tokens=90,
        do_sample=True,
        temperature=0.8,
        top_p=0.9,
        num_return_sequences=1
    )

    generated_text = result[0]["generated_text"]

    # Remove the prompt from the generated output to keep only the story.
    story = generated_text.replace(prompt, "").strip()

    # If the model output is too short or unclear, use a backup story.
    if len(story.split()) < 30:
        story = create_backup_story(caption)

    # Limit the story to around 100 words.
    words = story.split()
    if len(words) > 100:
        story = " ".join(words[:100]) + "."

    return story


# ---------------------------------------------------------
# Backup story generator
# This function creates a simple story if the AI text model
# does not generate a good enough result.
# ---------------------------------------------------------
def create_backup_story(caption):
    """
    Create a backup child-friendly story using the image caption.

    Args:
        caption: The image caption generated from the image.

    Returns:
        A simple 50-100 word story.
    """
    story = (
        f"Once upon a time, there was {caption}. "
        "It was a bright and happy day. A little friend looked around and found "
        "something wonderful to explore. With a big smile and a brave heart, "
        "the friend went on a small adventure. Along the way, everyone learned "
        "to be kind, curious, and helpful. At the end of the day, they all felt "
        "proud and happy."
    )

    return story


# ---------------------------------------------------------
# Convert story text to speech
# This function uses gTTS to convert the generated story into
# an MP3 audio file.
# ---------------------------------------------------------
def convert_text_to_speech(story_text):
    """
    Convert the story text into an audio file.

    Args:
        story_text: The generated story.

    Returns:
        The path of the generated MP3 audio file.
    """
    tts = gTTS(text=story_text, lang="en")

    # Create a temporary MP3 file for the story audio.
    temp_audio_file = tempfile.NamedTemporaryFile(delete=False, suffix=".mp3")
    tts.save(temp_audio_file.name)

    return temp_audio_file.name


# ---------------------------------------------------------
# Validate uploaded image
# This function checks whether the uploaded file can be opened
# as an image.
# ---------------------------------------------------------
def open_uploaded_image(uploaded_file):
    """
    Open and validate the uploaded image file.

    Args:
        uploaded_file: File uploaded through Streamlit.

    Returns:
        A PIL Image object.
    """
    try:
        image = Image.open(uploaded_file)
        image = image.convert("RGB")
        return image

    except Exception:
        st.error("Oops! 😢 This file does not look like a valid image. Please upload a JPG or PNG picture.")
        return None


# ---------------------------------------------------------
# Main Streamlit App
# This is the main user interface of the application.
# ---------------------------------------------------------
def main():
    """
    Main function that controls the Streamlit app layout and workflow.
    """

    # App title and introduction
    st.title("🌈 AI Storytelling App for Kids")

    st.markdown(
        """
        <div class="tip-box">
        👋 Hello, little storyteller!  
        Upload a picture, and I will create a magical story for you.  
        Then you can listen to the story too! 📖🔊
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    # Image uploader
    uploaded_file = st.file_uploader(
        "📷 Choose a picture to begin your story adventure!",
        type=["jpg", "jpeg", "png"]
    )

    # If the user has not uploaded an image yet, show a friendly message.
    if uploaded_file is None:
        st.info("Please upload a picture first. A fun story is waiting for you! ✨")
        return

    # Open and validate the uploaded image.
    image = open_uploaded_image(uploaded_file)

    if image is None:
        return

    # Display the uploaded image.
    st.image(
        image,
        caption="Your uploaded picture 🖼️",
        use_container_width=True
    )

    st.write("")

    # Big button for children to generate the story.
    generate_button = st.button("✨ Make My Story! ✨")

    if generate_button:
        try:
            # Load Hugging Face models.
            with st.spinner("Loading my imagination machine... 🧠✨"):
                captioning_model = load_captioning_model()
                story_model = load_story_model()

            # Generate image caption.
            with st.spinner("Looking carefully at your picture... 👀📷"):
                caption = generate_caption(image, captioning_model)

            st.markdown("### 🖼️ What I see in the picture")
            st.markdown(
                f"""
                <div class="caption-box">
                {caption}
                </div>
                """,
                unsafe_allow_html=True
            )

            st.write("")

            # Generate story.
            with st.spinner("Writing a magical story for you... 📖✨"):
                story = generate_story(caption, story_model)

            st.markdown("### 📖 Your Magical Story")
            st.markdown(
                f"""
                <div class="story-box">
                {story}
                </div>
                """,
                unsafe_allow_html=True
            )

            st.write("")

            # Convert story into speech.
            with st.spinner("Turning the story into audio... 🔊🎵"):
                audio_file_path = convert_text_to_speech(story)

            st.markdown("### 🔊 Listen to Your Story")
            st.audio(audio_file_path, format="audio/mp3")

            st.success("Your story is ready! Great job, little storyteller! 🌟")

            # Optional cleanup note:
            # Temporary audio files are created for playback.
            # Streamlit will manage the app session, but in larger apps,
            # you may want to delete old temporary files.

        except Exception as error:
            # Friendly error handling for children and clear debugging information.
            st.error("Oh no! Something went wrong while making the story. 😢")
            st.warning("Please try another image or click the button again.")

            # Show technical details for the teacher or developer.
            with st.expander("Show error details for debugging"):
                st.write(error)


# ---------------------------------------------------------
# Run the app
# This ensures the main function runs when app.py is executed.
# ---------------------------------------------------------
if __name__ == "__main__":
    main()
